DELIMITER $$

CREATE FUNCTION IF NOT EXISTS ID()
RETURNS CHAR(8) NO SQL
BEGIN
	RETURN LEFT(MD5(RAND()),8);
END$$

CREATE FUNCTION IF NOT EXISTS CALCULATE_CART_PRICE(userId CHAR(8))
RETURNS DECIMAL(10,2) DETERMINISTIC
BEGIN
	DECLARE total DECIMAL(10,2);
	SELECT SUM(g.price * c.quantity) INTO total FROM Carts c
	JOIN BoardGames g ON c.gameId = g.id
	WHERE c.userId = userId;
	RETURN total;
END$$

CREATE FUNCTION IF NOT EXISTS LOAN_REMAINING_DAYS(loanId CHAR(8))
RETURNS INT DETERMINISTIC
BEGIN
	DECLARE remaining INT;
	SELECT DATEDIFF(max_return_date, CURDATE()) INTO remaining FROM Loans
	WHERE id = loanId;
	RETURN remaining;
END$$

CREATE FUNCTION IF NOT EXISTS GAME_ORDERS_COUNT(gameId CHAR(8))
RETURNS INT DETERMINISTIC
BEGIN
	DECLARE total INT;
	SELECT SUM(DISTINCT o.userId) into total FROM Orders o
	JOIN OrderItems i ON i.orderId = o.id
	WHERE i.gameId = gameId;
	RETURN total;
END$$ 

DELIMITER ;